import { spawn } from "node:child_process";
import { access, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const selectors = process.argv.slice(2);
if (selectors.length === 0) {
  throw new Error(
    "Usage: node process-lessons.mjs <lesson-id|chapter:N> [...selectors]",
  );
}

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectDirectory = resolve(scriptDirectory, "..");
const repositoryRoot = resolve(projectDirectory, "../..");
const outline = JSON.parse(
  await readFile(join(projectDirectory, "inputs/course-outline.json"), "utf8"),
);
const inventory = JSON.parse(
  await readFile(join(projectDirectory, "inputs/media-inventory.json"), "utf8"),
);
const manifestPath = join(projectDirectory, "manifest.json");
const statePath = join(projectDirectory, "processing-state.json");
const lessons = outline.chapters.flatMap((chapter) =>
  chapter.lessons.map((lesson) => ({
    ...lesson,
    chapterId: chapter.id,
    chapterTitle: chapter.title,
    contentType: lesson.contentType ?? outline.defaultContentType,
  })),
);
const lessonById = new Map(lessons.map((lesson) => [lesson.id, lesson]));
const inventoryById = new Map(
  inventory.items.map((item) => [item.lessonId, item]),
);
const selectedIds = new Set();

for (const selector of selectors) {
  if (selector.startsWith("chapter:")) {
    const chapterId = selector.slice("chapter:".length);
    const chapterLessons = lessons.filter(
      (lesson) => lesson.chapterId === chapterId,
    );
    if (chapterLessons.length === 0) {
      throw new Error(`Unknown chapter selector: ${selector}`);
    }
    for (const lesson of chapterLessons) selectedIds.add(lesson.id);
    continue;
  }
  if (!lessonById.has(selector)) {
    throw new Error(`Unknown lesson ID: ${selector}`);
  }
  selectedIds.add(selector);
}

const selectedLessons = lessons.filter((lesson) => selectedIds.has(lesson.id));
const exists = async (path) =>
  access(path)
    .then(() => true)
    .catch(() => false);
const run = (command, args, options = {}) =>
  new Promise((resolvePromise, reject) => {
    const child = spawn(command, args, {
      cwd: repositoryRoot,
      env: process.env,
      stdio: ["inherit", options.stdout ?? "inherit", "inherit"],
    });
    child.once("error", reject);
    child.once("exit", (code, signal) => {
      if (signal) {
        reject(new Error(`${command} terminated by ${signal}.`));
        return;
      }
      if (code !== 0) {
        reject(new Error(`${command} exited with code ${code}.`));
        return;
      }
      resolvePromise();
    });
  });
const readState = async () => {
  if (!(await exists(statePath))) {
    return { version: 1, lessons: {} };
  }
  return JSON.parse(await readFile(statePath, "utf8"));
};
const updateState = async (lessonId, values) => {
  const state = await readState();
  state.lessons[lessonId] = {
    ...(state.lessons[lessonId] ?? {}),
    ...values,
    updatedAt: new Date().toISOString(),
  };
  await writeFile(statePath, `${JSON.stringify(state, null, 2)}\n`, "utf8");
};
const recordGeneration = async ({
  lesson,
  inventoryItem,
  promptPath,
  notePath,
  responsePath,
  compressedPath,
  compression,
}) => {
  const response = JSON.parse(await readFile(responsePath, "utf8"));
  if (!response.id) {
    throw new Error(`Response for ${lesson.id} has no request ID.`);
  }
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  if (manifest.generations.some((entry) => entry.requestId === response.id)) {
    return response;
  }
  const inputs = [inventoryItem.path];
  if (compressedPath) inputs.push(compressedPath);
  inputs.push(promptPath);
  manifest.generations.push({
    kind: "understanding",
    provider: "zenmux",
    model: response.model ?? "google/gemini-3.6-flash",
    createdAt: response.created
      ? new Date(response.created * 1000).toISOString()
      : new Date().toISOString(),
    requestId: response.id,
    inputs,
    outputs: [notePath, responsePath],
    parameters: {
      lessonId: lesson.id,
      contentType: lesson.contentType,
      compression,
      streamed: response.streamed === true,
      baseUrl: process.env.ZENMUX_BASE_URL ?? "https://zenmux.ai/api/v1",
      reasoningEffort: "low",
      temperature: 0.2,
      maxTokens: 12000,
      usage: response.usage ?? null,
    },
    notes: "Draft generated by the resumable course processor.",
  });
  await writeFile(
    manifestPath,
    `${JSON.stringify(manifest, null, 2)}\n`,
    "utf8",
  );
  return response;
};

for (const lesson of selectedLessons) {
  const inventoryItem = inventoryById.get(lesson.id);
  if (!inventoryItem) {
    throw new Error(`No media inventory item for ${lesson.id}.`);
  }
  const promptPath = `work/algorithm-interview-course-notes/prompts/${lesson.id}.md`;
  const notePath = `projects/algorithm-interview-course-notes/notes/lessons/${lesson.id}.md`;
  const responsePath = `${notePath}.response.json`;
  const absoluteNotePath = join(repositoryRoot, notePath);
  const absoluteResponsePath = join(repositoryRoot, responsePath);
  const noteExists = await exists(absoluteNotePath);
  const responseExists = await exists(absoluteResponsePath);

  if (noteExists !== responseExists) {
    throw new Error(
      `${lesson.id} has only one of note/response; inspect it before retrying.`,
    );
  }
  if (noteExists && responseExists) {
    process.stdout.write(`[skip] ${lesson.id} already has a response.\n`);
    await run(
      process.execPath,
      [join(scriptDirectory, "validate-notes.mjs"), lesson.id],
      { stdout: "ignore" },
    );
    const currentState = await readState();
    await updateState(lesson.id, {
      status:
        currentState.lessons[lesson.id]?.status === "reviewed"
          ? "reviewed"
          : "understood",
      validation: "valid",
    });
    continue;
  }

  process.stdout.write(`[render] ${lesson.id} ${lesson.title}\n`);
  await run(
    process.execPath,
    [join(scriptDirectory, "render-prompt.mjs"), lesson.id],
    { stdout: "ignore" },
  );

  let compression = "none";
  let compressedPath = null;
  let inputPath = inventoryItem.path;
  const zenmuxArgs = ["zenmux"];

  if (lesson.contentType === "article") {
    zenmuxArgs.push(
      "chat",
      "--prompt-file",
      promptPath,
      "--model",
      "google/gemini-3.6-flash",
    );
  } else {
    const originalStats = await stat(join(repositoryRoot, inventoryItem.path));
    const requestedCompressedPath = `work/algorithm-interview-course-notes/compressed/${lesson.id}.mp4`;
    const requestedStrongCompressedPath = `work/algorithm-interview-course-notes/compressed/${lesson.id}-strong.mp4`;
    const absoluteCompressedPath = join(
      repositoryRoot,
      requestedCompressedPath,
    );
    const absoluteStrongCompressedPath = join(
      repositoryRoot,
      requestedStrongCompressedPath,
    );
    if (await exists(absoluteStrongCompressedPath)) {
      inputPath = requestedStrongCompressedPath;
      compressedPath = requestedStrongCompressedPath;
      compression = "strong";
    } else if (await exists(absoluteCompressedPath)) {
      inputPath = requestedCompressedPath;
      compressedPath = requestedCompressedPath;
      compression = "balanced";
    }

    zenmuxArgs.push("understand", "--input", inputPath);
    if (!compressedPath && originalStats.size > 50 * 1024 * 1024) {
      compression = "balanced";
      compressedPath = requestedCompressedPath;
      zenmuxArgs.push(
        "--compress",
        "balanced",
        "--compressed-out",
        requestedCompressedPath,
      );
    }
    zenmuxArgs.push(
      "--prompt-file",
      promptPath,
      "--model",
      "google/gemini-3.6-flash",
    );
  }

  zenmuxArgs.push(
    "--stream",
    "--extra",
    '{"temperature":0.2,"max_tokens":12000,"reasoning_effort":"low"}',
    "--out",
    notePath,
  );
  process.stdout.write(
    `[request] ${lesson.id} ${lesson.contentType} compression=${compression}\n`,
  );
  await updateState(lesson.id, { status: "processing" });
  await run("pnpm", zenmuxArgs, { stdout: "ignore" });

  if (
    !(await exists(absoluteNotePath)) ||
    !(await exists(absoluteResponsePath))
  ) {
    throw new Error(`${lesson.id} completed without both output files.`);
  }
  let note = await readFile(absoluteNotePath, "utf8");
  if (!note.startsWith("---\n") && note.startsWith("lessonId:")) {
    note = `---\n${note}`;
    await writeFile(absoluteNotePath, note, "utf8");
  }
  const response = await recordGeneration({
    lesson,
    inventoryItem,
    promptPath,
    notePath,
    responsePath,
    compressedPath,
    compression,
  });
  try {
    await run(
      process.execPath,
      [join(scriptDirectory, "validate-notes.mjs"), lesson.id],
      { stdout: "ignore" },
    );
  } catch (error) {
    await updateState(lesson.id, {
      status: "needs_review",
      validation: "invalid",
      requestId: response.id,
    });
    throw error;
  }
  await updateState(lesson.id, {
    status: "understood",
    validation: "valid",
    requestId: response.id,
  });
  process.stdout.write(`[done] ${lesson.id} request=${response.id}\n`);
}
